#!/usr/bin/env python3
"""Private references: nothing in the published tree names one operator's setup.

The two documentation checkers read Python prose only. This one reads every file
git would publish, whatever its kind (Markdown, YAML, shell, HTML, C, Python code
and strings alike), because a host name in an example config or a home path in a
README leaks the same way a comment does.

Two kinds of finding:

  * **Shapes**, which hold for any operator and so can be published: an absolute
    path under a home or a cluster mount (`/home/<user>/...`, `/mnt/<fs>/...`), a
    run code in the shape the referent rule's `[cite]` section defines, a board
    envelope id (a `#` and three or more digits). The run-code and envelope patterns are read from
    `tools/referents_allowlist.txt`, so both checkers agree on what a citation is.
  * **Values**, read from the operator's local profile (`profile.toml` in `local/`, or
    the file `STIGMERGEIA_PROFILE` names): the node host, the remote user, every
    remote directory, and the operator's own home directory. A published list of
    those would defeat keeping them out, so they live only in the gitignored
    profile, and on a machine without one (CI) this half is skipped and says so.

Usage
-----
    python -m tools.check_private_refs [--json receipts/private-refs.json] [--report-only]

Exit 0: clean. Exit 1: findings. Exit 2: the check could not run.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tomllib
from dataclasses import asdict, dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ALLOWLIST = REPO_ROOT / "tools" / "referents_allowlist.txt"
DEFAULT_PROFILE = REPO_ROOT / "local" / "profile.toml"

# Files that carry these shapes on purpose, each with the reason it may.
EXEMPT: dict[str, str] = {
    "tools/check_private_refs.py": "defines the shapes it looks for",
    "tools/referents_allowlist.txt": "defines the run-code and envelope shapes",
    "tests/test_gate_fixtures.py": "the corpus of strings each checker must catch",
    "tests/test_private_refs.py": "the corpus of strings this checker must catch",
    "uv.lock": "generated by uv; package metadata only",
}
# Stylesheets and pages are full of hex colours, which share the envelope-id shape.
COLOR_SUFFIXES = {".html", ".css", ".svg"}
BINARY_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".ico", ".woff", ".woff2", ".so", ".db", ".pdf"}

# An absolute path into a home directory or a shared mount. The placeholder forms
# (a home directory written as `<user>` or `you`) are examples a reader substitutes.
ABS_PATH = re.compile(r"(?<![\w.~])/(?:home|mnt|net|scratch|data|gpfs|lustre|beegfs)/(?!<|you\b|user\b|me\b)[A-Za-z0-9_.-]+")
ALLOWLIST_CITE_MARK = re.compile(r"(?m)^# A run of the author's own experiments")


@dataclass(frozen=True)
class Finding:
    path: str
    line: int
    kind: str
    text: str


def published_files(repo: Path) -> list[Path]:
    """What git would publish: tracked files plus untracked ones not ignored."""
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
            capture_output=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError) as e:
        raise RuntimeError(f"cannot list the tree with git: {e}") from e
    names = sorted({n for n in out.decode().split("\0") if n})
    return [repo / n for n in names if not n.startswith("vendor/")]


def shape_patterns(allowlist: Path = ALLOWLIST) -> list[tuple[str, re.Pattern[str]]]:
    """The run-code and envelope-id shapes from the referent allowlist's own block."""
    text = allowlist.read_text()
    m = ALLOWLIST_CITE_MARK.search(text)
    if not m:
        raise RuntimeError(f"{allowlist}: the run-code block this checker reads is missing")
    block = text[m.start():].split("\n[", 1)[0]
    pats = [ln for ln in block.splitlines() if ln.strip() and not ln.startswith("#")]
    if len(pats) < 2:
        raise RuntimeError(f"{allowlist}: expected run-code and envelope patterns, found {len(pats)}")
    return [("run-code" if "#" not in p else "envelope-id", re.compile(p)) for p in pats] + [("abs-path", ABS_PATH)]


def profile_values(path: Path) -> list[str]:
    """Every string in the local profile that names this operator's setup, plus
    their home directory. Short values (a core range, a port) are dropped: they
    would match ordinary text and identify nothing."""
    if not path.is_file():
        return []
    try:
        data = tomllib.loads(path.read_text())
    except (OSError, tomllib.TOMLDecodeError) as e:
        raise RuntimeError(f"{path}: cannot read the local profile: {e}") from e
    found: set[str] = {str(Path.home())}

    def walk(v: object) -> None:
        if isinstance(v, dict):
            for x in v.values():
                walk(x)
        elif isinstance(v, list):
            for x in v:
                walk(x)
        elif isinstance(v, str) and len(v) >= 4 and not re.fullmatch(r"[0-9,\- ]+", v):
            found.add(v.rstrip("/"))
    walk(data)
    return sorted(found, key=len, reverse=True)


def scan(repo: Path, profile: Path) -> tuple[list[Finding], int, bool]:
    shapes = shape_patterns()
    values = profile_values(profile)
    value_res = [re.compile(r"(?<![\w.-])" + re.escape(v) + r"(?![\w-])") for v in values]
    findings: list[Finding] = []
    files = 0
    for f in published_files(repo):
        rel = f.relative_to(repo).as_posix()
        if rel in EXEMPT or f.suffix in BINARY_SUFFIXES or not f.is_file():
            continue
        try:
            text = f.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        files += 1
        for n, line in enumerate(text.splitlines(), 1):
            for kind, rx in shapes:
                if kind == "envelope-id" and f.suffix in COLOR_SUFFIXES:
                    continue  # a hex colour there, not a post
                for m in rx.finditer(line):
                    findings.append(Finding(rel, n, kind, m.group(0)))
            for rx in value_res:
                if rx.search(line):
                    findings.append(Finding(rel, n, "profile-value", "<a value from the local profile>"))
                    break
    return findings, files, bool(values)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="check_private_refs.py", description=__doc__.split("\n\n")[0])
    ap.add_argument("--json", type=Path, help="write the receipt here")
    ap.add_argument("--report-only", action="store_true", help="print the receipt and exit 0")
    ap.add_argument("--profile", type=Path, default=Path(os.environ.get("STIGMERGEIA_PROFILE", DEFAULT_PROFILE)))
    a = ap.parse_args(argv)
    try:
        findings, files, have_profile = scan(REPO_ROOT, a.profile)
    except RuntimeError as e:
        print(f"check_private_refs: {e}", file=sys.stderr)
        return 2
    print("private references")
    print(f"  files scanned: {files}")
    print(f"  profile values: {'checked' if have_profile else 'SKIPPED (no local profile here; shapes only)'}")
    print(f"  findings: {len(findings)}")
    for f in findings:
        print(f"    {f.path}:{f.line} [{f.kind}] {f.text}")
    print(f"  verdict: {'PASS' if not findings else 'FAIL'}")
    if a.json:
        a.json.parent.mkdir(parents=True, exist_ok=True)
        a.json.write_text(json.dumps({"files": files, "profile_checked": have_profile,
                                      "findings": [asdict(f) for f in findings]}, indent=2))
    return 0 if (a.report_only or not findings) else 1


if __name__ == "__main__":
    sys.exit(main())
